-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.departments
(
    dept_no character(4) NOT NULL,
    dept_name character varying NOT NULL,
    PRIMARY KEY (dept_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character(4) NOT NULL
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.dept_manager
(
    dept_no character(4),
    emp_no integer NOT NULL,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.employees
(
    emp_no integer NOT NULL,
    emp_title character(5) NOT NULL,
    birth_date date NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    sex character(1) NOT NULL,
    hire_date date NOT NULL,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.salaries
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.titles
(
    title_id character(5) NOT NULL,
    title character varying NOT NULL,
    PRIMARY KEY (title_id)
)
WITH (
    OIDS = FALSE
);
END;